### PR TITLE
initial commit to development

### PR DESCRIPTION
**Pull request by ngodi**

### CODE REVIEW

**Comment by ngodi** [comment]
thanks for the review @oluwoleilesanmi , can you please check the universal css reset in line 1 of the style.css...

**Comment by oluwoleilesanmi** [comment]
- This is good and works but in light of `separation of concern` it is better to separate such functionality into a different file. 
- Proceed to your next project its a :+1:  from me, but in subsequent projects consider using a dedicated file to reset your selectors.

**Comment by ngodi** [comment]
ok, thnx, I got it, will you merge then?

**Comment by oluwoleilesanmi** [comment]
- Go ahead and merge the project.

**Pull request merged**
